ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-alpine as base

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY . .

RUN npm run build

FROM node:${NODE_VERSION}-alpine

WORKDIR /app

COPY --from=base /app/.output /app

ENV HOST 0.0.0.0
ENV PORT 3000

EXPOSE 3000

CMD ["node", "./server/index.mjs"]