name: CI

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test

  build:
    name: Build Docker image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only build on push to main
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/inputstudio/nuxt3-starter # Modify this to your own image name
          tags: |
            type=raw,value=latest
            type=sha
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry # Can be replaced with any other registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          push: false # Only build, set to true to push
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
